In [88]:
np.random.seed(0)
X = np.random.randint(2, size=(10, 4))
y = np.array([0,0,0,0,1,1,1,1,1,1])

In [89]:
X

array([[0, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 1, 0]])

In [90]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [91]:
from sklearn.naive_bayes import BernoulliNB
model_bern = BernoulliNB().fit(X, y)

In [92]:
model_bern.classes_

array([0, 1])

In [93]:
model_bern.class_count_

array([4., 6.])

In [94]:
model_bern.class_log_prior_

array([-0.91629073, -0.51082562])

In [96]:
np.exp(model_bern.class_log_prior_)

array([0.4, 0.6])

In [77]:
model_bern.feature_count_

array([[2., 4., 3., 1.],
       [2., 3., 5., 3.]])

트레이닝 데이터가 다음과 같을때 bernoulli naive bayesian을 사용하여 다음 $x_{new}$ 에 대해 각각의 y에 대한 조건부 확률을 구한다, 단 a=1로 smoothing을 해야한다.

In [105]:
X = np.array([[1, 1, 0],
             [1, 0, 0],
             [0, 0, 1],
             [0, 1, 1]])
y = np.array([0, 0, 1, 1])
x_new = np.array([[1, 0, 0]])

In [106]:
from sklearn.naive_bayes import BernoulliNB
model_bern = BernoulliNB().fit(X, y)

In [107]:
model_bern.classes_

array([0, 1])

In [108]:
model_bern.class_count_

array([2., 2.])

In [109]:
model_bern.class_log_prior_

array([-0.69314718, -0.69314718])

In [110]:
fc = model_bern.feature_count_
fc

array([[2., 1., 0.],
       [0., 1., 2.]])

In [111]:
fc / np.repeat(model_bern.class_count_[:, np.newaxis], 3, axis=1)

array([[1. , 0.5, 0. ],
       [0. , 0.5, 1. ]])

In [112]:
fc / np.repeat(model_bern.class_count_[:, np.newaxis], 3, axis=1)

array([[1. , 0.5, 0. ],
       [0. , 0.5, 1. ]])

In [113]:
theta = (fc + 1) / np.repeat(model_bern.class_count_[:, np.newaxis] + 2 , 3, axis=1)
theta

array([[0.75, 0.5 , 0.25],
       [0.25, 0.5 , 0.75]])

In [114]:
pred = (theta**x_new)* (1-theta)**(1-x_new)
pred

array([[0.75, 0.5 , 0.75],
       [0.25, 0.5 , 0.25]])

In [115]:
pred = pred.prod(axis=1) * np.exp(model_bern.class_log_prior_)
pred / pred.sum()

array([0.9, 0.1])