In [25]:

def binary_search(lst, cond):
    '''
    (Optional) 이 함수를 반드시 구현할 필요는 없습니다. 즉, 이 함수는 채점에 포함되지 않습니다. 
	이진탐색을 활용하여 lst 내에서 cond 조건을 만족하는 최소의 원소를 반환하는 함수를 작성하세요.
	lst 는 오름차순으로 정렬되어있다고 가정해도 좋습니다. 
    
    ex) binary_search([1,2,3,4,5], lambda x: x>1) returns 2
    '''
    
    '''
    target : 찾을 값
    start : 시작 인덱스
    end : 끝 인덱스
    data : 데이터
    '''
 
    # 시작, 끝 인덱스 설정
    start = 0
    end = len(lst) - 1

    # 시작이 끝보다 크거나 같을때까지 반복
    
    rmin = end
    print(rmin)
    while start <= end:
        # 중간 인덱스 구하기
        mid = (start + end) // 2
    
        print(mid)
        # 조건에 맞다면
        if cond(lst[mid]):
            # 최저값인지 확인
            if rmin > lst[mid]:
                rmin = lst[mid]

        # 최저값보다 큰 인덱스(값)인지 확인하여 인덱스 조정
        if lst[mid] < rmin:
            start = mid + 1
        else: 
            end = mid -1 

       
   

    return rmin
    
def find_min_square_root(n):
    '''
	q^2 >= n 을 만족하는 최소의 q를 반환하는 함수를 작성하세요.
	경우에 따라 위에 제시되어 있는 binary_search 함수를 작성하여 사용하여도 좋습니다.
    ''' 
    
    sqrt = n**0.5
    mod =  sqrt % 1
    if mod > 0:
        res = sqrt - mod + 1
    else :
        res = sqrt
    return res 
    



In [26]:
n = 11298
lst = list(range(1, n+1))
binary_search( lst, lambda x: x**2 >= n)

11297
5648
2823
1411
705
352
175
87
131
109
98
103
106
104
105


107

In [24]:
print(find_min_square_root(n))

107.0


In [27]:
32 * 32

1024

In [38]:
def binary_search(target, data):
    
    # 시작, 끝 인덱스 설정
    start = 0
    end = len(data) - 1

    # 시작이 끝보다 크거나 같을때까지 반복
    while start <= end:
        # 중간 인덱스 구하기
        mid = (start + end) // 2

        if data[mid] == target: # 찾았다면 함수를 끝내버린다.
            return mid 
        elif data[mid] < target: # 타겠값보다 큰경우, 인덱스 조정
            start = mid + 1
        else: # 타겟값보다 작은경우 , 인덱스 조정
            end = mid -1 
    return None

In [39]:
li = [i**2 for i in range(11)]
target = 9
idx = binary_search(target, li)

if idx:
    print(li[idx])
else:
    print("찾으시는 타겟 {}가 없습니다".format(target))

9


In [25]:
def binary_search_recursion(target, start, end, data):
    '''
    target : 찾을 값
    start : 시작 인덱스
    end : 끝 인덱스
    data : 데이터
    '''
    
    # 인덱스 오류 검사
    if start > end:
        return None

    # 다음 인덱스 찾기 (중간 인덱스)
    mid = (start + end) // 2

    # 중간인덱스의 값이 타겟값인경우 찾음
    if data[mid] == target:
        return mid
    # 타겠값보다 큰경우, 인덱스 조정하여 한번 더 수행
    elif data[mid] > target:
        end = mid - 1
    # 타겟값보다 작은경우 , 인덱스 조정하여 한번 더 수행
    else:
        start = mid + 1        

    return binary_search_recursion(target, start, end, data)

In [26]:
li = [i*3 for i in range(11)]
target = 6
idx = binary_search_recursion(target, 0, 10, li)

print(li)
print(idx)

5
2
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
2


In [3]:
def find_min_room(num_class, classes):
    #구현해주세요!
    
#last = 0
# result=[]
# for n in ncls:
#     if last < n[1]:
#         last = n[2]
#         result.append(n)
# len(result)

    # 시작시간 기준으로 정렬
    cls = sorted(classes, key=lambda start: start[1])  
    ncls = np.array(cls).T

    start = list(ncls[1])
    min_rooms = 0
    for end in ncls[2]:
        for st in start:
            # 이미 점유했다면 리스트에서 삭제함
            if st - end > 0: 
                start.remove(st) 
                min_rooms += 1
  
    min_rooms = num_class - min_rooms
    return min_rooms

def read_inputs():
    num_class = int(input())
    classes = []
    for i in range(num_class):
        line = [int(x) for x in input().split()]
        class_no = line[0]
        start = line[1]
        end = line[2]
        classes.append((class_no, start, end))

    return num_class, classes


In [159]:

classes = [[1,1,3],
          [2,2,5],
          [3,4,7],
          [4,1,8],
          [5,5,9],
          [6,8,10],
          [7,9,11],
          [8,11,14],
          [9,13,16]]


classes = [[6, 15, 21 ], 
            [7, 20, 25  ],
            [1, 3, 8  ],
            [3, 2, 14]  ,
            [8, 6, 27]  ,
            [2, 7, 13]  ,
            [4, 12, 18 ] ,
            [5, 6, 20]]

# classes = [[1, 1, 3],
#           [2, 2, 4],
#           [3, 3, 5],
#            [4, 5, 7]]

num_class= len(classes)

# 시작시간 기준으로 정렬
cls = sorted(classes, key=lambda start: start[1])  
ncls = np.array(cls)
ncls


# ans = find_min_room(num_class, classes)
# print(ans)

array([[ 3,  2, 14],
       [ 1,  3,  8],
       [ 8,  6, 27],
       [ 5,  6, 20],
       [ 2,  7, 13],
       [ 4, 12, 18],
       [ 6, 15, 21],
       [ 7, 20, 25]])

In [216]:
mintime = np.min(ncls[:,1])
maxtime = np.max(ncls[:,2])

rooms = np.zeros(shape=(1, maxtime))
res_dict = {}
for idx, n in enumerate(ncls):
     
    start = n[1]-1
    end = n[2]
        
    isfit=False 
    fit_idx = 0
    mindis = 9999
    mindis_idx = -1
    for j, room in enumerate(rooms):

        applyingtime = room[start:end]
        
        # 비어있다면
        if np.sum(applyingtime) == 0: 
            isfit = True 
           
            if j in res_dict.keys(): 
                times = res_dict[j]
                last = times[len(times)-1]
                dis =  n[1] - last[2]
                
                if (dis > 0) & (mindis > dis):
                    mindis = dis
                    fit_idx = j   
                    if dis == 1:
                        break
                       
    if isfit:
        # 있는지 체크
        if fit_idx in res_dict.keys(): 
            res_dict[fit_idx].append(n)
        else:
            res_dict[fit_idx] = [n] 

        rooms[fit_idx][start:end] = idx+1 
        
    else: 
        res_dict[len(rooms)] = [n] 
        
        newroom = np.zeros(shape=(maxtime))
        
        newroom[start:end] = idx+1
        rooms = np.vstack((rooms, newroom)) 
 
print(len(rooms))

5


In [210]:
res_dict

{0: [array([ 3,  2, 14]), array([ 6, 15, 21])],
 1: [array([1, 3, 8]), array([ 4, 12, 18]), array([ 7, 20, 25])],
 2: [array([ 8,  6, 27])],
 3: [array([ 5,  6, 20])],
 4: [array([ 2,  7, 13])]}

In [211]:
len(rooms), rooms

(5, array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 7., 7.,
         7., 7., 7., 7., 7., 0., 0., 0., 0., 0., 0.],
        [0., 0., 2., 2., 2., 2., 2., 2., 0., 0., 0., 6., 6., 6., 6., 6.,
         6., 6., 0., 8., 8., 8., 8., 8., 8., 0., 0.],
        [0., 0., 0., 0., 0., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [0., 0., 0., 0., 0., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [110]:
diff = np.diff(np.array([1,1,1,0,0]),n=1)
np.insert(diff, 0, 0)

array([ 0,  0,  0, -1,  0])

In [111]:
diff = np.diff(np.array([0,1,1,1,0]),n=1)
np.insert(diff, 0, 0)

array([ 0,  1,  0,  0, -1])

In [112]:
diff = np.diff(np.array([0,0,1,1,1]),n=1)
np.insert(diff, 0, 0)

array([0, 0, 1, 0, 0])

In [37]:
mintime = np.min(ncls[:,1])
maxtime = np.max(ncls[:,2])

rooms=[]
for n in ncls:

    #print(n)

    if len(rooms) == 0:
        rooms.append([n]) #첫 강의실 배정
        #print('new')
    else:

        isfit = False
        for i, room in enumerate(rooms):
            #print(i, room)

            if (room[0][1] > n[2]) | (room[len(room)-1][2] < n[1]):
                room.append(n)
                isfit = True 

            if isfit:
                #print('add')
                break

        if isfit == False:
            rooms.append([n])
            #print('new')
    #print('=====')
print(len(rooms))

5


In [27]:
rooms = []
for n in ncls:
    #print(n)
     
    if len(rooms)==0:
        rooms.append([n]) 
        #print('추가')
    else:
        # 강의실 배정 받았는지
        isfit = False 
        for i, room in enumerate(rooms):
            # 시간표
            #print(i, room) 
                 
            #강의 중간에 시간이 겹치는지 확인
            isduplicated=False
            for time in room:
                if (time[1] <= n[1]) & (time[2] >= n[1]) | (time[1] <= n[2]) & (time[2] >= n[2]):
                    isduplicated=True
                    break
                     
            # 겹치지 않았다면 새로 추가
            if isduplicated==False:
                #print('add',n)
                room.append(n)
                isfit = True #강의실 배정
                
        
        # 새로운강의실 배정
        if isfit == False:
            rooms.append([n])
            #print('추가')
     
    #print('=======')
print(len(rooms))

5


In [24]:
rooms, len(rooms)

([[array([ 3,  2, 14]), array([ 6, 15, 21])],
  [array([1, 3, 8]), array([ 4, 12, 18]), array([ 7, 20, 25])],
  [array([ 8,  6, 27])],
  [array([ 5,  6, 20])],
  [array([ 2,  7, 13]), array([ 6, 15, 21])]],
 5)